# Generated by Django 4.2.7 on 2023-11-17 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marathon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='checkpoint',
        ),
        migrations.CreateModel(
            name='RouteCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_from_start', models.FloatField()),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.checkpoint')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marathon.route')),
            ],
        ),
    ]
